controllers/PostController.php
<?php

namespace app\controllers;

use app\models\Category;
use Yii;
use app\models\TestForm;

class PostController extends AppController {

//    public $layout = 'basic';

    public function actionIndex() {
//        if (Yii::$app->request->isAjax){
//            debug($_POST);
//            debug(Yii::$app->request->post());
//            return 'done';
//        }

//        $post = TestForm::findOne(1);
//        $post->email = '45@s.com'; обновление данных в БД
//        $post->save();
//
//        $post->delete();

//        TestForm::deleteAll(['>', 'id', 3]); //удаление данных по условию

        $model = new TestForm();
//        $model->name = 'Author';
//        $model->email = 'a@a.ru';
//        $model->text = 'message';
//        $model->save(); //save() запускает валидацию. отправить false. если валидация не нужна

//        if ( $model->load(Yii::$app->request->post()) ) {
////            debug($model);
////            die;
//            if ( $model->validate() ) { //проверка на валидацию введенных данных
//                Yii::$app->session->setFlash('success', 'Данные приняты'); //создание флеш-сообщения при успешной проверке
//                return $this->refresh(); //очистка страницы
//            } else {
//                Yii::$app->session->setFlash('error', 'Ошибка');
//            }
//        }

        if ( $model->load(Yii::$app->request->post()) ) {
//            debug($model);
//            die;
            if ( $model->save() ) { //проверка на валидацию введенных данных
                Yii::$app->session->setFlash('success', 'Данные приняты'); //создание флеш-сообщения при успешной проверке
                return $this->refresh(); //очистка страницы
            } else {
                Yii::$app->session->setFlash('error', 'Ошибка');
            }
        }

        return $this->render('test', compact('model'));
    }

    public function actionShow() {
        //$this->layout = 'basic';

        //1 шаг: find() - объект запроса
        //2 шаг: - настроить объект запроса (WHERE, ORDER BY, LIMIT, etc...)
        //3 шаг: all() - получение данных
        // SORT_ASC - 1-10; SORT_DESC - 10-1

//        $cats = Category::find()->all(); //запрос в БД на показ всей таблицы SELECT * FROM `posts`
//        $cats = Category::find()->orderBy(['id' => SORT_DESC])->all(); //запрос в БД с сортировкой
//        $cats = Category::find()->asArray()->all(); //asArray - получение данных из БД в виде массива
//        $cats = Category::find()->asArray()->where('id=1')->all(); //вывод с условием WHERE
//        $cats = Category::find()->asArray()->where(['id' => 1])->all(); //
//        $cats = Category::find()->asArray()->where(['like', 'title', 'кто'])->all(); //
//        $cats = Category::find()->asArray()->where(['<=', 'id', 5])->all(); //
//        $cats = Category::find()->asArray()->where(['<=', 'id', 15])->limit(2)->all(); //
//        $cats = Category::find()->asArray()->where(['<=', 'id', 15])->one(); //получение всех записей, но в массиве только одна
//        $cats = Category::find()->asArray()->where(['<=', 'id', 15])->count(); //получение количества записей
//        $cats = Category::find()->asArray()->count(); //получение количества записей

//        $cats = Category::findOne(['id' => 2]); //получение количества записей
//        $cats = Category::findAll(['id' => 2]); //получение количества записей

//        $query = "SELECT * FROM articles WHERE title LIKE '%кто%'";
//        $cats = Category::findBySql($query)->asArray()->all();

//        $query = "SELECT * FROM articles WHERE title LIKE :search";
//        $cats = Category::findBySql($query, [':search' => '%кто%'])->all();

        $cats = Category::findOne(6);

        return $this->render('show', compact('cats'));
    }

}

?>

views/layouts/basic.php
<?php
use app\assets\AppAsset;
use yii\helpers\Html;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!doctype html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <?php $this->registerCsrfMetaTags() ?>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

    <div class="wrap">
        <div class="container">
            <ul class="nav nav-pills">
                <li class="nav-item">
                    <?= Html::a('Главная', '/web/'); ?>
                </li>
                <li class="nav-item">
                    <?= Html::a('Статьи', ['post/index']); ?>
                </li>
                <li class="nav-item">
                    <?= Html::a('Статья', ['post/show']); ?>
                </li>
            </ul>

            <?= $content; ?>

        </div>
    </div>

    <h1>Hello, basic.php!</h1>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/']],
            ['label' => 'Articles', 'url' => ['/post/index']],
            ['label' => 'About', 'url' => ['/about']],
            ['label' => 'Contact', 'url' => ['/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>